version: "3.9"
services:
  web:
    build: ./api
    image: zkrkiki2305/dctest:0.1
    ports:
      - 3000:3000
    depends_on: 
      - pg
    volumes: 
      - ./api/src:/usr/app/src
    environment: 
      - PG_CONNECTION_STRINGpostgres://${POSTGRES_USER}

  pg: 
    image: postgres:latest
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_DB 
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGDATA=/var/lib/postg
    #volumes:
     # - ./_volumes/pgdata:/var/lib/postgresql/data

    